In [1]:
import pandas as pd
import numpy as np

**Problem:**

You are given the following dataset:
1. **Audible Data** : https://1drv.ms/u/s!AiqdXCxPTydhoog8ckLN-6Cw55fzIg?e=EWgZ5d

Your task is to:
- Find the problems with the datasets.
- Define the Data Quality Dimensions.
- Try to clean the datasets.

In [150]:
audible_data=pd.read_csv('audible_uncleaned.csv',na_values=['Free'])

In [ ]:
audible_data.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

# Dirty Data
1 . Issues in author, narrator column.
2. date column is string
3. price column is string and for free values there is NaN
4. star column has both rating and stars
5. star column is string
6. time should


# Messy Data:
1. stars and rating are in the same column they can be seprated
2. time should be as a seprate column with total mintues

Solving issue for author column and replacing extra text before the original name.

In [151]:
audible_data['author']=audible_data['author'].str.split(':').str.get(1)

In [153]:
audible_data.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

Solving issue for narrator column and replacing extra text before the original name.

In [154]:
audible_data['narrator']=audible_data['narrator'].str.split(':').str.get(1)

Changing datetime column back to datetime object

In [155]:
audible_data['releasedate']=pd.to_datetime(audible_data['releasedate'])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_20028\3703364217.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  audible_data['releasedate']=pd.to_datetime(audible_data['releasedate'])

In [156]:
audible_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87488 non-null  str
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  datetime64[us]
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87151 non-null  str
dtypes: datetime64[us](1), object(2), str(5)
memory usage: 5.3+ MB

Filling NaNs with 0 and changing the dataype of price column

In [157]:
audible_data['price']=audible_data['price'].str.replace(',',"")

In [158]:
audible_data['price']=audible_data['price'].str.split('.').str.get(0)

In [166]:
audible_data['price']=audible_data['price'].fillna(0)

In [169]:
audible_data['price']=audible_data['price'].astype('int32')

,name,author,narrator,time,releasedate,language,stars,price
983,Ringo & the Yogi,PrasunRoy,SiddhantaPinto,5 hrs and 18 mins,2019-11-19,English,4 out of 5 stars4 ratings,0
1414,The Velveteen Rabbit,MargeryWilliams,RichardArmitage,24 mins,2020-08-14,English,4.5 out of 5 stars91 ratings,0
1513,Billi Aur Moosarani [Cat and Musrani],Shivani,SarahHashmi,26 mins,2021-10-14,Hindi,Not rated yet,0
2932,Pariyon Ki Kahaniya [Fairy Tales],JacobGrimm,AnuradhaChauhan,2 hrs and 15 mins,2021-08-12,Hindi,Not rated yet,0
4547,101 Best Indian Fables for Children,StutiGupta,SunandhaRaghunathan,2 hrs and 26 mins,2019-03-12,English,4 out of 5 stars3 ratings,0
...,...,...,...,...,...,...,...,...
80021,FREE: The Undead,RRHaywood,DanMorgan,1 hr and 3 mins,2015-02-24,English,4 out of 5 stars8 ratings,0
81198,Supporters. Le Pilote,"PierreNiboyet,AudreyPoiret",BorisRehlinger,24 mins,2020-10-29,french,Not rated yet,0
82644,Boots Belts Berets,TanushreePodder,RannvijaySinghSingha,6 hrs and 59 mins,2019-08-27,English,4.5 out of 5 stars158 ratings,0
86771,Canada Is Awesome,NeilPasricha,NeilPasricha,34 mins,2018-09-10,English,4.5 out of 5 stars29 ratings,0
86927,Osez l'aventure avec Mike Horn. Le pilote,"MikeHorn,CharlesAudier","MikeHorn,CharlesAudier",24 mins,2022-11-01,french,Not rated yet,0

In [188]:
audible_data['rating']=audible_data['stars'].str.split('stars').str.get(0)

In [193]:
audible_data['stars']=audible_data['stars'].str.split('stars').str.get(1).str.split(" ").str.get(0)

In [194]:
audible_data

,name,author,narrator,time,releasedate,language,stars,price,rating
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,2008-04-08,English,34,468,5 out of 5
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,2018-01-05,English,41,820,4.5 out of 5
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,2020-06-11,English,38,410,4.5 out of 5
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,2021-05-10,English,12,615,4.5 out of 5
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,2010-01-13,English,181,820,4.5 out of 5
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,7 hrs and 34 mins,2017-09-03,English,NaN,596,Not rated yet
87485,The Alps,StephenO'Shea,RobertFass,10 hrs and 7 mins,2017-02-21,English,NaN,820,Not rated yet
87486,The Innocents Abroad,MarkTwain,FloGibson,19 hrs and 4 mins,2016-12-30,English,NaN,938,Not rated yet
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,4 hrs and 8 mins,2011-02-23,English,NaN,680,Not rated yet
87488,Havana,MarkKurlansky,FleetCooper,6 hrs and 1 min,2017-07-03,English,NaN,569,Not rated yet

In [195]:
audible_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87488 non-null  str
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  datetime64[us]
 5   language     87489 non-null  str
 6   stars        15072 non-null  object
 7   price        87489 non-null  int32
 8   rating       87489 non-null  object
dtypes: datetime64[us](1), int32(1), object(4), str(3)
memory usage: 5.7+ MB

In [196]:
audible_data['author'] = audible_data['author'].str.replace(r'(?<=[a-z])(?=[A-Z])', ' ', regex=True)
audible_data['narrator'] = audible_data['narrator'].str.replace(r'(?<=[a-z])(?=[A-Z])', ' ', regex=True)

In [200]:
audible_data['author'] = audible_data['author'].str.replace(r'(?<=\.)(?=[A-Z])', ' ', regex=True)
audible_data['narrator'] = audible_data['narrator'].str.replace(r'(?<=\.)(?=[A-Z])', ' ', regex=True)

In [218]:
audible_data['stars']=audible_data['stars'].fillna(0)

In [216]:
audible_data['stars']=audible_data['stars'].str.replace(',','')

In [219]:
audible_data['stars']=audible_data['stars'].astype('int32')

In [226]:
hours = audible_data['time'].str.extract(r'(\d+) hr', expand=False).fillna(0).astype(int)
minutes = audible_data['time'].str.extract(r'(\d+) min', expand=False).fillna(0).astype(int)
audible_data['total_mintues']=(hours*60)+minutes

In [228]:
audible_data.drop(columns='time',inplace=True)

In [231]:
audible_data

,name,author,narrator,releasedate,language,stars,price,rating,total_mintues
0,Geronimo Stilton #11 & #12,Geronimo Stilton,Bill Lobely,2008-04-08,English,34,468,5 out of 5,140
1,The Burning Maze,Rick Riordan,Robbie Daymond,2018-01-05,English,41,820,4.5 out of 5,788
2,The Deep End,Jeff Kinney,Dan Russell,2020-06-11,English,38,410,4.5 out of 5,123
3,Daughter of the Deep,Rick Riordan,Soneela Nankani,2021-05-10,English,12,615,4.5 out of 5,676
4,"The Lightning Thief: Percy Jackson, Book 1",Rick Riordan,Jesse Bernstein,2010-01-13,English,181,820,4.5 out of 5,600
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Chris Stewart,Chris Stewart,2017-09-03,English,0,596,Not rated yet,454
87485,The Alps,Stephen O'Shea,Robert Fass,2017-02-21,English,0,820,Not rated yet,607
87486,The Innocents Abroad,Mark Twain,Flo Gibson,2016-12-30,English,0,938,Not rated yet,1144
87487,A Sentimental Journey,Laurence Sterne,Anton Lesser,2011-02-23,English,0,680,Not rated yet,248
87488,Havana,Mark Kurlansky,Fleet Cooper,2017-07-03,English,0,569,Not rated yet,361